name: Deploy to Pantheon

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: open_web_build
    permissions:
      deployments: write
      contents: read
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push to Pantheon
        uses: pantheon-systems/push-to-pantheon@0.9.0
        with:
          ssh_key: ${{ secrets.PANTHEON_SSH_KEY }}
          machine_token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
          site: ${{ secrets.PANTHEON_SITE }}
          git_commit_message: "Deploy ${{ github.sha }} from GitHub Actions"
          delete_old_environments: ${{ github.ref == 'refs/heads/main' }}
